#!/usr/bin/env python3
"""
build_report.py — reproducible assembler for the final interactive report.

Reads the hand-authored template `report_template.html` and produces a single,
fully self-contained `report.html`:

  * embeds the two display/body fonts (Fraunces + Newsreader, roman + italic
    variable woff2) as base64 `@font-face` sources, and
  * embeds all 13 figures as `data:` URIs — SVG (crisp vector) for every figure
    except ppi_network + rank_abundance, which are embedded as base64 PNG per
    the build spec (the ppi_network SVG is ~1.5 MB / 25k nodes).

Figure titles and captions are pulled verbatim from the verified digest
`report_facts.json` (the content source of truth) so no numbers are invented
here. The template carries `%%TOKEN%%` placeholders; this script substitutes
them and writes the result. It never modifies any pipeline script, result, or
figure — it only READS the committed figures to embed copies.

Usage:
    python3 build_report.py            # writes report.html next to the template
"""
from __future__ import annotations

import base64
import html
import json
import re
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent                       # proteomics_de/report
FIGDIR = HERE.parent / "results" / "figures"                 # proteomics_de/results/figures
FONTDIR = HERE / "assets" / "fonts"
TEMPLATE = HERE / "report_template.html"
OUTPUT = HERE / "report.html"

# report_facts.json is the committed digest beside this script, generated by
# build_facts.py. An explicit path may still be passed as argv[1].
#
# There used to be a hardcoded absolute scratchpad path AHEAD of the committed
# file here, left over from the session that first authored the digest. It only
# ever worked because that path is absent: any future session that happened to
# land on the same UUID would have silently built the report from a foreign
# facts file, with no warning and no trace in the output. Removed.
FACTS_CANDIDATES = [
    HERE / "report_facts.json",
]


def load_facts(override: Path | None = None) -> dict:
    """Load the facts digest, preferring an explicit `override` path.

    Takes the override as an argument rather than mutating FACTS_CANDIDATES in
    place, which is what main() used to do: a second call in the same process
    then inherited the first call's argv and could read an unrelated file.

    An override that does not exist is an error, not a reason to fall back. If
    a caller names a facts file, building from a *different* one behind their
    back is the same silent-wrong-source failure the removed scratchpad path
    would have caused.
    """
    if override is not None:
        if not override.exists():
            raise SystemExit(f"facts file not found: {override}")
        return json.loads(override.read_text())
    for c in FACTS_CANDIDATES:
        if c.exists():
            return json.loads(c.read_text())
    raise SystemExit("report_facts.json not found; pass its path as argv[1].")


def b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def get_dims(path: Path, fmt: str) -> tuple[int, int]:
    """Return the intrinsic (width, height) in integer pixels for a figure.

    Used to set explicit width/height attributes on the <img> so the browser
    can reserve layout space (aspect-ratio inferred from the attributes) and
    avoid content jump when eagerly-loaded plates paint — without hardcoding
    any figure's dimensions here.
    """
    if fmt == "png":
        data = path.read_bytes()
        if data[:8] != b"\x89PNG\r\n\x1a\n":
            raise SystemExit(f"not a valid PNG: {path}")
        w, h = struct.unpack(">II", data[16:24])
        return w, h
    if fmt == "svg":
        text = path.read_text()
        m = re.search(r'viewBox="[-\d.]+\s+[-\d.]+\s+([\d.]+)\s+([\d.]+)"', text)
        if not m:
            raise SystemExit(f"no viewBox found in {path}")
        return round(float(m.group(1))), round(float(m.group(2)))
    raise SystemExit(f"unknown figure format: {fmt}")


# ---- font tokens ------------------------------------------------------------
FONTS = {
    "%%FONT_FRAUNCES_ROMAN%%": "fraunces-roman.woff2",
    "%%FONT_FRAUNCES_ITALIC%%": "fraunces-italic.woff2",
    "%%FONT_NEWSREADER_ROMAN%%": "newsreader-roman.woff2",
    "%%FONT_NEWSREADER_ITALIC%%": "newsreader-italic.woff2",
}

# ---- figure plate metadata --------------------------------------------------
# key -> (basename-without-ext, embed-format, figure-number, tag, hypothesis?)
FIGURES = [
    ("intensity_distributions", "svg", 1,  "QC · distributions",     False),
    ("missing_values",          "svg", 2,  "QC · missingness",       False),
    ("sample_correlation",      "svg", 3,  "QC · reproducibility",   False),
    ("rank_abundance",          "png", 4,  "QC · dynamic range",     False),
    ("volcano",                 "svg", 5,  "Track A · limma",        True),
    ("ma_plot",                 "svg", 6,  "Track A · limma",        True),
    ("ora_dotplot",             "svg", 7,  "Track A · enrichment",   True),
    ("pca_qc",                  "svg", 8,  "QC only · n = 4",        False),
    ("sample_dendrogram",       "svg", 9,  "QC only · n = 4",        False),
    ("heatmap_top_de",          "svg", 10, "Track B · leads",        True),
    ("ppi_network",             "png", 11, "Track B · leads",        True),
    ("gsea_top",                "svg", 12, "Track B · leads",        True),
    ("upset",                   "svg", 13, "Track B · leads",        True),
]

MIME = {"svg": "image/svg+xml", "png": "image/png"}


def facts_by_key(facts: dict) -> dict:
    out = {}
    for f in facts["figures"]:
        key = Path(f["file"]).stem            # "figures/volcano.png" -> "volcano"
        out[key] = f
    return out


def make_plate(key, fmt, num, tag, hypo, meta) -> str:
    src_path = FIGDIR / f"{key}.{fmt}"
    if not src_path.exists():
        raise SystemExit(f"missing figure file: {src_path}")
    w, h = get_dims(src_path, fmt)
    data_uri = f"data:{MIME[fmt]};base64,{b64(src_path)}"
    title = html.escape(meta["title"])
    caption = html.escape(meta["caption"])
    warn = '<span class="fw">hypothesis-generating</span>' if hypo else ""
    return (
        '<div class="plate">\n'
        '  <figure>\n'
        f'    <div class="imgwrap"><img loading="eager" decoding="async" width="{w}" height="{h}" alt="{title}" src="{data_uri}"></div>\n'
        '    <figcaption>\n'
        f'      <div class="ftag"><span>Figure&nbsp;{num:02d}</span><span>{html.escape(tag)}</span>{warn}</div>\n'
        f'      <div class="fttl">{title}</div>\n'
        f'      <p>{caption}</p>\n'
        '    </figcaption>\n'
        '  </figure>\n'
        '</div>'
    )


def main(argv: list[str] | None = None) -> None:
    args = sys.argv[1:] if argv is None else argv
    facts = load_facts(Path(args[0]) if args else None)
    fmeta = facts_by_key(facts)

    html_text = TEMPLATE.read_text()

    # 1) fonts
    for token, fname in FONTS.items():
        fp = FONTDIR / fname
        if not fp.exists():
            raise SystemExit(f"missing font file: {fp}")
        html_text = html_text.replace(token, f"data:font/woff2;base64,{b64(fp)}")

    # 2) figure plates
    embedded = 0
    for key, fmt, num, tag, hypo in FIGURES:
        token = f"%%PLATE_{key}%%"
        if token not in html_text:
            raise SystemExit(f"template is missing placeholder {token}")
        html_text = html_text.replace(token, make_plate(key, fmt, num, tag, hypo, fmeta[key]))
        embedded += 1

    # 3) sanity: no unresolved tokens remain.
    # The character class must cover BOTH cases: the pattern was [A-Z0-9_], so a
    # lowercase token (%%plate_volcano%%) sailed straight through this check and
    # shipped as literal text in the report. Every real token happens to be
    # upper-case, which is exactly why the hole went unnoticed.
    leftover = re.findall(r"%%[A-Za-z0-9_]+%%", html_text)
    if leftover:
        raise SystemExit(f"unresolved template tokens remain: {sorted(set(leftover))}")

    OUTPUT.write_text(html_text)

    # 4) self-check report
    size = OUTPUT.stat().st_size
    external = [
        u for u in re.findall(r'(?:src|href)\s*=\s*"([^"]+)"', html_text)
        if u.startswith("http://") or u.startswith("https://")
    ]
    print(f"wrote {OUTPUT}")
    print(f"  size: {size/1024/1024:.2f} MB ({size:,} bytes)")
    print(f"  figures embedded: {embedded}/13")
    print(f"  external src/href references (should be none): {len(external)}")
    for u in external:
        print(f"    ! {u}")


if __name__ == "__main__":
    main()
