"""Tests for the byte-freeze gate itself.

The gate is safety-critical: every later package's acceptance test is "the
frozen outputs did not move." A gate that is silently always-green would let a
real regression through, so these tests exercise BOTH directions -- it must
stay green on legitimate regeneration noise and go red on genuine change.
"""

import shutil
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tools"))
import freeze  # noqa: E402

MANIFEST = REPO_ROOT / "proteomics_de" / "tests" / "expected" / "outputs.sha256"


def test_manifest_exists_and_parses():
    entries = freeze.read_manifest(MANIFEST)
    # Deliberately an explicit number: adding a scientific artifact should be a
    # conscious act that updates this manifest, not something silently absorbed.
    # Grew during the D7 enrichment re-run: the previously-uncached STRING and
    # g:Profiler responses are now recorded under results/enrichment/raw/.
    # 75 -> 77: regulated_up.csv/regulated_down.csv added (PI export stage).
    # 77 -> 80: regulated_up_partial.csv/regulated_down_partial.csv/
    # qualitative_changes.csv added (D17 supplementary export stage).
    # 80 -> 84: ipa_input_extended.csv/.txt and ipa_qualitative_up.txt/
    # ipa_qualitative_down.txt added (D18 extended IPA export stage). Purely
    # additive -- the other 80 hashes are unchanged.
    # 84 -> 85: ipa_background_measured.txt added (D19 IPA Reference Set, the
    # same stage). Again purely additive -- the other 84 hashes are unchanged.
    assert len(entries) == 85, f"expected 85 frozen artifacts, got {len(entries)}"
    modes = {mode for _sha, mode in entries.values()}
    assert modes <= {"raw", "svg-canon", "ts-canon"}, modes


def test_manifest_freezes_outputs_not_sources():
    """The gate must not freeze source code.

    Freezing .py/.R files makes the gate fail by construction whenever anyone
    refactors -- which is the activity the gate exists to make safe.
    """
    for rel in freeze.read_manifest(MANIFEST):
        assert not rel.endswith((".py", ".R")), f"source file frozen: {rel}"
        assert rel.startswith("proteomics_de/results/") or "_limma_" in rel, rel


def test_tree_matches_manifest():
    ok, changed, missing, extra = freeze.verify(MANIFEST, REPO_ROOT)
    assert not changed, f"frozen outputs drifted: {changed}"
    assert not missing, f"frozen outputs missing: {missing}"
    assert not extra, f"untracked artifacts present: {extra}"
    # 80 -> 84: the D18 extended IPA export stage's 4 files.
    # 84 -> 85: D19's ipa_background_measured.txt, from the same stage.
    # Stays 85 after results/ipa_analysis/ was committed: those are QIAGEN IPA's
    # own exports, excluded from the walk by policy rather than added here.
    # See FROZEN_EXCLUDE_DIRS in tools/freeze.py.
    assert len(ok) == 85


def test_ipa_analysis_is_excluded_by_policy_and_says_so():
    """QIAGEN IPA exports sit outside the gate -- visibly, not silently.

    They are the output of a manual external tool. The pipeline cannot
    regenerate them, so --verify-frozen could never meaningfully check them,
    and a legitimate re-export changes their bytes -- which would report as
    drift after every IPA run and train people to ignore the gate.

    Asserted as a property of the directory rather than against a file list, so
    a future IPA export is covered the moment it lands. The counterpart
    assertion -- that this exclusion did not swallow a real pipeline output --
    is the ipa_background_measured.txt check below.
    """
    ipa_dir = REPO_ROOT / "proteomics_de" / "results" / "ipa_analysis"
    assert ipa_dir.is_dir(), "fixture directory vanished"

    excluded = dict(freeze.excluded_files(REPO_ROOT))
    frozen = {p.relative_to(REPO_ROOT).as_posix() for p in freeze.frozen_files(REPO_ROOT)}
    manifest = freeze.read_manifest(MANIFEST)

    on_disk = [p for p in ipa_dir.rglob("*") if p.is_file()]
    assert on_disk, "fixture directory is empty"
    for p in on_disk:
        rel = p.relative_to(REPO_ROOT).as_posix()
        assert rel in excluded, f"IPA export not excluded: {rel}"
        assert "external tool output" in excluded[rel], excluded[rel]
        assert rel not in frozen, f"IPA export still walked as frozen: {rel}"
        assert rel not in manifest, f"IPA export leaked into the manifest: {rel}"


def test_ipa_inputs_we_generate_stay_frozen():
    """The exclusion must not spread to the ipa_* files the pipeline produces.

    results/ipa_analysis/ is IPA's output; results/ipa_*.{csv,txt} are OUR
    inputs to it, are regenerated by the export stage, and are exactly the kind
    of artifact the freeze exists for. An exclusion matched on "ipa" rather
    than on the directory would quietly drop all of them.
    """
    frozen = {p.relative_to(REPO_ROOT).as_posix() for p in freeze.frozen_files(REPO_ROOT)}
    manifest = freeze.read_manifest(MANIFEST)
    for rel in (
        "proteomics_de/results/ipa_background_measured.txt",
        "proteomics_de/results/ipa_input_extended.txt",
        "proteomics_de/results/ipa_qualitative_up.txt",
        "proteomics_de/results/ipa_qualitative_down.txt",
    ):
        assert (REPO_ROOT / rel).is_file(), rel
        assert rel in frozen, f"pipeline output dropped from the freeze: {rel}"
        assert rel in manifest, f"pipeline output dropped from the manifest: {rel}"


def test_svg_canonicalization_absorbs_regeneration_noise(tmp_path):
    """matplotlib's <dc:date> and salted ids must not count as drift."""
    src = REPO_ROOT / "proteomics_de/results/figures/volcano.svg"
    a = tmp_path / "a.svg"
    shutil.copy(src, a)
    raw = a.read_bytes()

    b = tmp_path / "b.svg"
    b.write_bytes(
        raw.replace(b"<dc:date>", b"<dc:date>2099-01-01T00:00:00.000000", 1)
    )
    assert a.read_bytes() != b.read_bytes(), "fixture did not actually differ"
    assert freeze.digest(a)[0] == freeze.digest(b)[0]


def test_svg_canonicalization_still_catches_real_change(tmp_path):
    """A genuine plot change must change the hash."""
    src = REPO_ROOT / "proteomics_de/results/figures/volcano.svg"
    a = tmp_path / "a.svg"
    shutil.copy(src, a)
    raw = a.read_bytes()

    marker = b'd="M '
    idx = raw.index(marker) + len(marker)
    b = tmp_path / "b.svg"
    b.write_bytes(raw[:idx] + b"9" + raw[idx + 1:])  # perturb one path coordinate
    assert freeze.digest(a)[0] != freeze.digest(b)[0]


def test_salted_ids_stay_distinct(tmp_path):
    """Renumbering must not collapse two distinct ids into one."""
    p = tmp_path / "x.svg"
    p.write_bytes(b'<g id="pabcdef0123"/><g id="p0123abcdef"/>')
    canon, mode = freeze.canonical_bytes(p)
    assert mode == "svg-canon"
    assert b"id0" in canon and b"id1" in canon


def test_raw_mode_is_byte_exact(tmp_path):
    p = tmp_path / "x.csv"
    p.write_text("a,b\n1,2\n")
    first = freeze.digest(p)[0]
    p.write_text("a,b\n1,3\n")
    assert freeze.digest(p)[0] != first
